site_name: 360Giving Covid Research
site_url: https://covidresearch.threesixtygiving.org
repo_url: https://github.com/ThreeSixtyGiving/covid-research
theme:
    name: null
    custom_dir: 'tsg_theme/'
nav:
  - Home: index.md
  - About: about.md
  - 'About the grants':
    - 'Size of grants': about-grants/size-of-grants.md
google_analytics: ['G-L5GXFV0X1E', 'covidresearch.threesixtygiving.org']