site_name: 'UK Covid relief and recovery grants: data analysis'
site_url: https://covidresearch.threesixtygiving.org
repo_url: https://github.com/ThreeSixtyGiving/covid-research
theme:
    name: null
    custom_dir: 'tsg_theme/'
nav:
  - Home: index.md
  - About this report: about.md
  - Key findings: key-findings.md
  - Overview: overview.md
  - 'About the grants':
    - about-grants/over-time.md
    - about-grants/size-of-grants.md
    - about-grants/grant-duration.md
  - 'Grant recipients':
    - grant-recipients/recipient-types.md
    - grant-recipients/recipient-size.md
    - grant-recipients/proportion-of-charities.md
    - grant-recipients/proportion-of-income.md
    - grant-recipients/charity-themes.md
    - grant-recipients/charity-groups.md
    - grant-recipients/people-supported.md
  - 'Funding patterns':
    - funding-patterns/changing-spend.md
    - funding-patterns/multiple-funders.md
    - funding-patterns/previous-funding.md
    - funding-patterns/geography.md
    - funding-patterns/regrants.md
  - Conclusion: conclusion.md
  - Methodology: method.md
  - 'Appendices':
    - about-funds.md
    - all-funds.md
    - download.md
  - 'Report [PDF]': data/covid_grants_research.pdf
google_analytics: ['G-L5GXFV0X1E', 'covidresearch.threesixtygiving.org']
matomo: 30